const moreProperties = [
    {
        id: 4,
        src: './flat1.jpg',
        viewsCount: '12,648',
        starsCount: '3.9',
        mainTitle: 'Sushant lok 2, gurgaon',
        mainDate: 'Mar 5 - 10',
        mostLiked: false,
        wishListed: true,
    },
    {
        id: 2,
        src: './flat2.jpg',
        viewsCount: '411,172',
        starsCount: '5.0',
        mainTitle: 'Rainbow Heights, HSR',
        mainDate: 'Jun 10 - 15',
        mostLiked: true,
        wishListed: false,
    },
    {
        id: 7,
        src: './flat3.jpg',
        viewsCount: '8,402',
        starsCount: '4.3',
        mainTitle: 'Walden Colorado, US',
        mainDate: 'Apr 1 - 7',
        mostLiked: true,
        wishListed: true,
    },
    {
        id: 1,
        src: './flat4.jpg',
        viewsCount: '25,648',
        starsCount: '2.8',
        mainTitle: 'Poggibonsi, Itay',
        mainDate: 'Dec 20 - 25',
        mostLiked: false,
        wishListed: false,
    },
    {
        id: 6,
        src: './flat1.jpg',
        viewsCount: '5,321',
        starsCount: '4.7',
        mainTitle: 'Sushant lok 2, gurgaon',
        mainDate: 'May 8 - 13',
        mostLiked: true,
        wishListed: false,
    },
    {
        id: 3,
        src: './flat2.jpg',
        viewsCount: '32,402',
        starsCount: '3.2',
        mainTitle: 'Rainbow Heights, HSR',
        mainDate: 'Jan 15 - 20',
        mostLiked: false,
        wishListed: true,
    },
    {
        id: 5,
        src: './flat3.jpg',
        viewsCount: '10,542',
        starsCount: '3.82',
        mainTitle: 'Poggibonsi, Itay',
        mainDate: 'Feb 12 - 18',
        mostLiked: true,
        wishListed: true,
    },
];

export default moreProperties;
